### PR TITLE
C++ SD v1.5 pipeline

### PR DESCRIPTION
**Pull request by yangsu2022**

### CODE REVIEW

**Comment by yury-gorbachev** [comment]
Could we move this to different path?
@Wovchena , what would be correct format? ImageGeneration/StableDiffusion1_5?

**Comment by Wovchena** [comment]
Following the style proposed in https://github.com/openvinotoolkit/openvino.genai/pull/9 it should be `image_generation/stable_diffusion_1_5/cpp`

**Comment by yangsu2022** [comment]
updated with "image_generation/stable_diffusion_1_5/cpp" and use new trapezoidal implementation without Boost

**Comment by wenjiew** [comment]
@xipingyan to take a look at the code and provide comments if there is any. Thanks!

**Comment by xipingyan** [comment]
It is a good example. It contains model convert, compress, independent C++ reference codes.

**Pull request merged**
