### PR TITLE
Port from 24.6 release to master

### PR DESCRIPTION
**Pull request by pavel-esir**
- ~https://github.com/openvinotoolkit/openvino.genai/pull/1302~ (didn't port this PR because of the issue CVS-159227)
- https://github.com/openvinotoolkit/openvino.genai/pull/1262
- https://github.com/openvinotoolkit/openvino.genai/pull/1336
- https://github.com/openvinotoolkit/openvino.genai/pull/1331

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
You need to replace runner for `cpp-greedy_causal_lm-redpajama-3b-chat` to `ubuntu-20.04-8-cores` to fix that job

**Comment by pavel-esir** [comment]
> You need to replace runner for `cpp-greedy_causal_lm-redpajama-3b-chat` to `ubuntu-20.04-8-cores` to fix that job

yes, sure. Just did it

**Comment by pavel-esir** [comment]
The remaining problem is caused by this https://github.com/openvinotoolkit/openvino.genai/pull/1302
In the fix we enforce streamer to not print last 4 bytes (just in case if they change after adding new tokens) this fixed a model but break streaming in python, because when symbols are cut in the middle they became invalid and python replaces them with `�`

In python streamer we get
>��������������������룅 encouraging룅 

instead of c++ streamer out

>룅튜룅튜룅튜룅튜룅튜룅 encouraging룅

Indeed the same issue now is in 2024.6, we just didn't see it because diff for mincpm is enable only on the master https://github.com/openvinotoolkit/openvino.genai/pull/1134

**Comment by pavel-esir** [comment]
Reverted that cherry pick and created a ticket to fix that separately CVS-159227
FYI @ilya-lavrenov

**Pull request merged**
