### PR TITLE
Update NNCF default configs

### PR DESCRIPTION
**Pull request by KodiaqQ**
**Updated NNCF defaults for:**

- dolly-v2-3b
- opt-2.7b
- red-pajama-incite-chat-3b-v1
- vicuna-7b-v1.5
- stablelm-tuned-alpha-3b

Based on the experiments from 135227

### CODE REVIEW

**Comment by Wovchena** [comment]
@eaidova is on vacation. Maybe @peterchen-intel can review it.

**Review by eaidova — APPROVED** [review]

**Comment by KodiaqQ** [comment]
@peterchen-intel, could you please re-run failed checks and merge PR?
cc @Wovchena

**Comment by peterchen-intel** [comment]
@Wovchena Can you please check the failure?

**Review by peterchen-intel — APPROVED** [review]

**Comment by Wovchena** [comment]
I expect https://github.com/openvinotoolkit/openvino.genai/pull/420 to fix this random fail. Restart it until the PR gets merged.

**Comment by KodiaqQ** [comment]
@Wovchena, I cannot restart the failed runs due to a lack of access. Could you please restart it? Thanks.

**Pull request merged**
