### PR TITLE
disable torch.compile when beckend is not specified

### PR DESCRIPTION
**Pull request by eaidova**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Please, don't merge without passed CI and without merge queue.
Because of it all PRs in merge queue have to be revalidated.

**Comment by eaidova** [comment]
@ilya-lavrenov, ok. but without these changes all of them will failed anyway

**Comment by ilya-lavrenov** [comment]
this commit 009486e28f77743ca84aabf7abd63df68fa3ea9f (latest on master before your one) has passed CI, so master is not broken.

**Comment by eaidova** [comment]
it passed before update on the next openvino nightly (16.10), compatibility bug will appear when llm bench tests starts run on this openvino package

**Pull request merged**
