### PR TITLE
Bump product version to 2024.5

### PR DESCRIPTION
**Pull request by akladiev**
Connected PRs to be merged first: https://github.com/openvinotoolkit/openvino/pull/26309, https://github.com/openvinotoolkit/openvino_tokenizers/pull/238

### CODE REVIEW

**Comment by akladiev** [comment]
@Wovchena, please, take a look. Should we do something with tokenizers submodule after version update here?

**Comment by Wovchena** [comment]
Yes. That's the reason of pre-commit fails. Tokenizers submodule should be updated after tokenizers PR is merged.

```
    openvino_tokenizers_VERSION (2024.4.0.0) is not equal to
    PY_BUILD_CMAKE_PACKAGE_VERSION (2024.5.0.0)
```

**Comment by ilya-lavrenov** [comment]
> Yes. That's the reason of pre-commit fails. Tokenizers submodule should be updated after tokenizers PR is merged.
> 
> ```
>     openvino_tokenizers_VERSION (2024.4.0.0) is not equal to
>     PY_BUILD_CMAKE_PACKAGE_VERSION (2024.5.0.0)
> ```

Looks like it compares versions of different projects 
Fix is https://github.com/openvinotoolkit/openvino_tokenizers/pull/239

**Comment by ilya-lavrenov** [comment]
Replaced by https://github.com/openvinotoolkit/openvino.genai/pull/807

**Pull request closed without merging**
