### PR TITLE
Throw exception when MD5 is not aligned instead of warning

### PR DESCRIPTION
**Pull request by wgzintel**

### CODE REVIEW

**Comment by peterchen-intel** [comment]
Need to wait for the fixing of this CVS-140095

**Comment by yeonbok** [comment]
Hello, from the gpu plugin's perspective, we do not guarantee first and second inference's bit exactness. It is because we have two types of kernels : 1) shape agnostic kernels that are executed first and build more optimized static kernels. 2) Once optimized static kernels are ready later, they are executed. However these kernels have different configuration (e.g.,, tile size) which causes compuation result different because the order of multipy & add is different.  Please refer to the issue [138890](https://jira.devtools.intel.com/browse/CVS-138890).

**Comment by peterchen-intel** [comment]
@wgzintel  Let's always compare to the previous one instead of comparing to warm-up.

**Comment by peterchen-intel** [comment]
> Hello, from the gpu plugin's perspective, we do not guarantee first and second inference's bit exactness. It is because we have two types of kernels : 1) shape agnostic kernels that are executed first and build more optimized static kernels. 2) Once optimized static kernels are ready later, they are executed. However these kernels have different configuration (e.g.,, tile size) which causes compuation result different because the order of multipy & add is different. Please refer to the issue [138890](https://jira.devtools.intel.com/browse/CVS-138890).

@yeonbok  Can you please share the link for the documentation to explain this difference?

**Review by peterchen-intel — APPROVED** [review]

**Pull request merged**
