### PR TITLE
Verify phi-2

### LINKED ISSUE #274: [Good First Issue]: Verify phi-2 with GenAI text_generation
### Context

This task regards enabling tests for **phi-2**. You can find more details under openvino_notebooks [LLM question answering README.md](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/275-llm-question-answering).

Please ask general questions in the main issue at https://github.com/openvinotoolkit/openvino.genai/issues/259

### What needs to be done?

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

### Example Pull Requests

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

Described in the main Discussion issue at: https://github.com/openvinotoolkit/openvino.genai/issues/259

### Ticket

_No response_

### PR DESCRIPTION
**Pull request by qxprakash**
This should close #274 , I have updated the model list , and added tests taking reference from issue description at #259  , @p-wysocki @ilya-lavrenov @pavel-esir in the readme I have added phi separately , since there are other phi models as well , like phi-1.5 which can be added in the future , please let me know if anything else can be done.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by qxprakash** [comment]
@p-wysocki should I also verify Phi-1.5 ?

**Comment by p-wysocki** [comment]
Thank you for your contribution!

Sure, @Wovchena mentioned that contributors may propose their own models. :) Do you want me to create a Good First Issue for you?

**Comment by qxprakash** [comment]
Thanks for the guidance @p-wysocki , I will create an issue by myself , based on the template for verifying models.

**Comment by qxprakash** [comment]
Ok sure @p-wysocki

**Pull request merged**
